#\u9879\u76EE\u914D\u7F6E
server:
  port: 8080
  servlet:
    jsp:
      init-parameters:
        development: true # \u5F00\u542FJSP\u8C03\u8BD5\u6A21\u5F0F\uFF0C\u4FEE\u6539JSP\u65E0\u9700\u91CD\u542F
    context-path: /hospital # \u4E0A\u4E0B\u6587\u8DEF\u5F84

# Spring MVC \u914D\u7F6E
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://127.0.0.1:3306/hospital?useSSL=false
  mvc:
    view:
      prefix: /WEB-INF/page/ # \u9875\u9762\u524D\u7F00
      suffix: .jsp # \u9875\u9762\u540E\u7F00
    #  static-path-pattern: /**
    hiddenmethod:
      filter:
        enabled: true

# Mybatis-Plus \u914D\u7F6E
mybatis-plus:
  mapper-locations: classpath:mapper/**/*.xml # Mapper XML \u626B\u5305\u8DEF\u5F84
  type-aliases-package: com.dj.hospital.pojo # \u7C7B\u522B\u540D
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl # \u6253\u65E5\u5FD7
